### ISSUE TITLE
Update docker-compose (or something)

### ISSUE THREAD

**Issue by m-novitsky** [donBarbos/telegram-bot-template#156]
It would be nice to add something like this to the dockerfile (docker-compose): alembic upgrade head
Or use may be 'prestart.sh' that could be mount.

**Comment by donBarbos** [comment]
If you have ideas or suggestions on how to implement this, you can send a PR
You can also send examples of how this is done in other projects

**Comment by m-novitsky** [comment]
I'm not sure if this is an elegant solution, but I just added this to the docker-compose file (into bot service section):
`command: ["sh","-c","sleep 10 && alembic upgrade head && python -m bot"]`

**Comment by donBarbos** [comment]
I haven't found solution that satisfies me, so I'll leave it as it is for now.

If you have any suggestions, you can reopen the issue.
